### ISSUE TITLE
node-lint@*' is not in the npm registry.

### ISSUE THREAD

**Issue by WolfgangFahl** [niebert/Wiki2Reveal#2]
see http://wiki.bitplan.com/index.php/Reveal-Slides#Wiki2Reveal
```
npm install -g browserify watchify uglify-js doctoc
```
works

**Comment by niebert** [comment]
browserify watchify ...  is not necessary for Wiki2Reveal  but you are right, if you fork Wiki2Reveal or build on `wtf_wikipedia`  with browserify et.al. just add the packages globally or add them to `package.json` with `--save-dev`. I would recommend to build with build tools / tool chain of the repository you fork from. The parsoid parser is bidirectional and may serve your needs.
