### ISSUE TITLE
use mediawiki API instead of wiki2html

### ISSUE THREAD

**Issue by WolfgangFahl** [niebert/Wiki2Reveal#4]
the mediawiki api allows to get the html for a page directly. Main.js seems to use a different approach. Isn't that redudant and a source of incompability in the html result?

**Comment by niebert** [comment]
Good suggestion, thank you Wolfgang. Using the media wiki API directly may help to get directly the HTML. But there is still parsing require for the HTML source to do the conversion of HTML into the RevealJS syntax of the DOM tree. Also math syntax needs handling. So parsing the HTML tree can be also a challenge when the rendering Wiki source text of HTML pages in the mediawiki changes. Currently I use [Wiki2Reveal](https://niebert.githu.io/Wiki2Reveal) for [lectures in  mathematics with the backboard annotations](https://de.wikiversity.org/wiki/Kurs:Topologische_Invertierbarkeitskriterien) .

**Comment by WolfgangFahl** [comment]
@niebert  - Engelbert thank you for the response.
https://www.semantic-mediawiki.org/wiki/User:WolfgangFahl shows presentations of the last few years i did which revolve around the use of the mediawiki-api.  http://mediawiki-japi.bitplan.com/index.php/Main_Page was the first Java solution i created and it was integrated into some RESTFul services via Jersey. E.g. https://github.com/BITPlan/com.bitplan.wikitask is  based on this which together with the http://www.rythmengine.org/ template engine used to be the main style of working with mediawiki content. 

Recently I started being a research at RWTH Aachen i5 and also changed the focus from Java to python So the wikipush toolkit is based on the MediaWiki API but used python We do embed the solution into web services e.g. https://confident.dbis.rwth-aachen.de/dblpconf/ and http://ptp.bitplan.com/ do use this approach. The main usage is in https://pypi.org/project/pyWikiCMS/ though which separates the web frontend from the wiki backend.

**Comment by WolfgangFahl** [comment]
I tried solving the reveal problem as in https://github.com/BITPlan/pyWikiCMS/issues/20 but had no success so far.

**Comment by niebert** [comment]
Maybe a sound integration of  the current version [wtf_wikipedia](https://github.com/spencermountain/wtf_wikipedia) by Spencer Kelly will create a better foundation for Wiki2Reveal in the future. MediaWiki moved from a Javascript based Parsoid to bidirectional Python parser. So you did a better job than I did with the Javascript prototype of Wiki2Reveal.
Parsoid is a very solid parser maybe you could use Parsoid. 
* Split into sections 
* split the section into paragraphs,
* use the [down arrows to scroll down the page](https://revealjs.com/#/2)  per paragraph in RevealJS if the page does not fit on slide,
best regards,
